SELECT
    TRIM(CUSTOMER_ID) AS CUSTOMER_ID,
    TRIM(CUSTOMER_UNIQUE_ID) AS CUSTOMER_UNIQUE_ID,
    TRIM(CUSTOMER_ZIP_CODE_PREFIX) AS CUSTOMER_ZIP_CODE_PREFIX,
    INITCAP(TRIM(CUSTOMER_CITY)) AS CUSTOMER_CITY,
    UPPER(TRIM(CUSTOMER_STATE)) AS CUSTOMER_STATE
FROM {{ source('olist_raw', 'customers') }}
WHERE CUSTOMER_ID IS NOT NULL
