SELECT
    TRIM(PRODUCT_ID) AS PRODUCT_ID,
    COALESCE(LOWER(TRIM(PRODUCT_CATEGORY_NAME)), 'unknown') AS PRODUCT_CATEGORY_NAME,
    PRODUCT_NAME_LENGHT AS PRODUCT_NAME_LENGTH,
    PRODUCT_DESCRIPTION_LENGHT AS PRODUCT_DESCRIPTION_LENGTH,

    PRODUCT_PHOTOS_QTY,
    PRODUCT_WEIGHT_G,
    PRODUCT_LENGTH_CM,
    PRODUCT_HEIGHT_CM,
    PRODUCT_WIDTH_CM

FROM {{ source('olist_raw', 'products') }}
WHERE PRODUCT_ID IS NOT NULL
