SELECT
    TRIM(ORDER_ID) AS ORDER_ID,
    TRIM(CUSTOMER_ID) AS CUSTOMER_ID,
    LOWER(TRIM(ORDER_STATUS)) AS ORDER_STATUS,

    ORDER_PURCHASE_TIMESTAMP,
    ORDER_APPROVED_AT,
    ORDER_DELIVERED_CARRIER_DATE,
    ORDER_DELIVERED_CUSTOMER_DATE,
    ORDER_ESTIMATED_DELIVERY_DATE,

    CAST(ORDER_PURCHASE_TIMESTAMP AS DATE) AS ORDER_PURCHASE_DATE

FROM {{ source('olist_raw', 'orders') }}
WHERE ORDER_ID IS NOT NULL
