SELECT
    TRIM(ORDER_ID) AS ORDER_ID,
    ORDER_ITEM_ID,
    TRIM(PRODUCT_ID) AS PRODUCT_ID,
    TRIM(SELLER_ID) AS SELLER_ID,
    SHIPPING_LIMIT_DATE,
    PRICE,
    COALESCE(FREIGHT_VALUE, 0) AS FREIGHT_VALUE,

FROM {{ source('olist_raw', 'order_items') }}
WHERE ORDER_ID IS NOT NULL
  AND ORDER_ITEM_ID IS NOT NULL
