SELECT
    TRIM(ORDER_ID) AS ORDER_ID,
    PAYMENT_SEQUENTIAL,
    LOWER(TRIM(PAYMENT_TYPE)) AS PAYMENT_TYPE,
    PAYMENT_INSTALLMENTS,
    PAYMENT_VALUE

FROM {{ source('olist_raw', 'order_payments') }}
WHERE ORDER_ID IS NOT NULL
