-- Geographical performance by state
SELECT
    R.REGION_NAME,
    R.STATE_NAME,
    E.CUSTOMER_STATE,

    SUM(E.ITEM_TOTAL_VALUE) AS TOTAL_REVENUE,
    COUNT(DISTINCT E.ORDER_ID) AS TOTAL_ORDERS,
    COUNT(DISTINCT E.CUSTOMER_UNIQUE_ID) AS UNIQUE_CUSTOMERS,
    AVG(E.FREIGHT_VALUE) AS AVG_FREIGHT_VALUE

FROM {{ ref('int_order_items_enriched') }} AS E

LEFT JOIN {{ ref('state_regions') }} AS R
    ON E.CUSTOMER_STATE = R.CUSTOMER_STATE

WHERE E.ORDER_STATUS = 'delivered'
GROUP BY
    R.REGION_NAME,
    R.STATE_NAME,
    E.CUSTOMER_STATE
