-- Actual category performance measured against the targets

SELECT
    C.PRODUCT_CATEGORY_NAME_ENGLISH,
    T.PRIORITY_LEVEL,

    C.TOTAL_REVENUE,
    T.TARGET_REVENUE,
    C.TOTAL_REVENUE - T.TARGET_REVENUE AS REVENUE_VARIANCE,

    C.TOTAL_ORDERS,
    T.TARGET_ORDERS,

    CASE
        WHEN T.TARGET_REVENUE IS NULL THEN 'NO TARGET SET'
        WHEN C.TOTAL_REVENUE >= T.TARGET_REVENUE THEN 'TARGET MET'
        ELSE 'BELOW TARGET'
    END AS TARGET_STATUS

FROM {{ ref('mart_category_performance') }} AS C

LEFT JOIN {{ ref('category_targets') }} AS T
    ON C.PRODUCT_CATEGORY_NAME_ENGLISH = T.PRODUCT_CATEGORY_NAME_ENGLISH
