-- Revenue and volume by product category.

SELECT
    PRODUCT_CATEGORY_NAME_ENGLISH,

    SUM(ITEM_TOTAL_VALUE) AS TOTAL_REVENUE,
    COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,
    COUNT(*) AS ITEMS_SOLD,
    COUNT(DISTINCT CUSTOMER_UNIQUE_ID) AS UNIQUE_CUSTOMERS,

    AVG(PRICE) AS AVG_ITEM_PRICE

FROM {{ ref('int_order_items_enriched') }}
WHERE ORDER_STATUS = 'delivered'
GROUP BY PRODUCT_CATEGORY_NAME_ENGLISH
