import json
from pathlib import Path
from models import UserProfile, Workout
import uuid


class JsonRepository:

    def __init__(self, filename="data/workout_log.json"):
        self.filename = Path(filename)
        if not self.filename.exists():
            self.save([], [])

    def load(self):
        with open(self.filename, "r") as f:
            return json.load(f)

    def save(self, users, workouts):
        data = {
            "users": [u.model_dump() for u in users],
            "workouts": [w.model_dump() for w in workouts]
        }
        with open(self.filename, "w") as f:
            json.dump(data, f, indent=4)

    # Users

    def generate_api_key(self):
        return str(uuid.uuid4())

    # Note: The API key is autogenerated and unique, but I also enforce that UID is unique, even though it will be provided by the user
    def create_user(self, user: UserProfile):
        data = self.load()
        users = [UserProfile(**u) for u in data["users"]]
        workouts = [Workout(**w) for w in data["workouts"]]
        # ensure unique user_id
        for u in users:
            if u.user_id == user.user_id:
                raise Exception("user_id already exists")
        # generate API key server-side
        user.api_key = self.generate_api_key()
        # ensure API key uniqueness
        while any(u.api_key == user.api_key for u in users):
            user.api_key = self.generate_api_key()
        users.append(user)
        self.save(users, workouts)
        return user

    def get_users(self):
        return [UserProfile(**u) for u in self.load()["users"]]

    def get_user(self, user_id: int):
        for user in self.get_users():
            if user.user_id == user_id:
                return user
        return None

    def update_user(self, updated_user: UserProfile):
        data = self.load()
        users = [UserProfile(**u) for u in data["users"]]
        workouts = [Workout(**w) for w in data["workouts"]]
        for i, user in enumerate(users):
            if user.user_id == updated_user.user_id:
                users[i] = updated_user
                self.save(users, workouts)
                return True
        return False

    def delete_user(self, user_id: int):
        data = self.load()
        users = [
            UserProfile(**u)
            for u in data["users"]
            if u["user_id"] != user_id
        ]
        workouts = [Workout(**w) for w in data["workouts"]]
        self.save(users, workouts)
        return True

    # Workouts

    def generate_workout_id(self):
        data = self.load()
        workouts = data["workouts"]
        if not workouts:
            return 1
        return max(w["workout_id"] for w in workouts) + 1

    def create_workout(self, workout: Workout):
        data = self.load()
        users = [UserProfile(**u) for u in data["users"]]
        workouts = [Workout(**w) for w in data["workouts"]]
        workout.workout_id = self.generate_workout_id() # ID is autogenerated
        workouts.append(workout)
        self.save(users, workouts)
        return workout

    def get_workouts(self):
        return [Workout(**w) for w in self.load()["workouts"]]

    def get_workout(self, workout_id: int):
        for workout in self.get_workouts():
            if workout.workout_id == workout_id:
                return workout
        return None

    def update_workout(self, updated_workout: Workout):
        data = self.load()
        users = [UserProfile(**u) for u in data["users"]]
        workouts = [Workout(**w) for w in data["workouts"]]
        for i, workout in enumerate(workouts):
            if workout.workout_id == updated_workout.workout_id:
                workouts[i] = updated_workout
                self.save(users, workouts)
                return True
        return False

    def delete_workout(self, workout_id: int):
        data = self.load()
        users = [UserProfile(**u) for u in data["users"]]
        workouts = [
            Workout(**w)
            for w in data["workouts"]
            if w["workout_id"] != workout_id
        ]
        self.save(users, workouts)
        return True